### PR TITLE
Email

### PR DESCRIPTION
**Pull request by zachMitchell**
Ready when you guys are! For the most part, i'm guessing there's only really one conflict we really need to handle if we decide to make the merge into web_ui

### CODE REVIEW

**Comment by zachMitchell** [comment]
so much for one conflict... XP

**Comment by JakeSimms33** [comment]
I'm pulling the code now to review later tonight

**Comment by zachMitchell** [comment]
The conflicts have now been tackled. It's ready to be pushed after review 👍

**Comment by jmknight2** [comment]
Everything seems like it should be good to go. Assuming all the problems with the PDF have been fixed, then we should be ready to merge.

**Pull request merged**
